### ISSUE TITLE
On Load does not work

### ISSUE THREAD

**Issue by sponno** [anijs/studio#1]
Looking through the config.js there is no condition for "load". And trying to get animations to work on load does not work. : (

**Comment by darielnoel** [comment]
Hi John thanks for sharing, if you want to execute some animations when the page is loaded please take a look to  [onRunFinished Event](https://github.com/anijs/anijs/wiki/Listening-events-from-document-and-window#onrunfinished-event). 

Anything else, we are on touch.

Best Regards, Dariel

**Comment by sponno** [comment]
Sorry you are spot on.  Just getting started with this.
I noticed that there are also 2x load events and 2x scroll events in the Chrome Plugin
![image](https://cloud.githubusercontent.com/assets/70642/3728687/701a6bd2-16ae-11e4-8a61-8480b34929e6.png)

**Comment by darielnoel** [comment]
No problem, you can ask anything, I'll try to help in whatever :) 

This problem would be fixed in the next version. I'll keep you informed.

Regards
